# Basic workflow
name: Python-testing

# Controls
on:
  # Triggers the workflow on push or pull request events on "main" branch
  push:
    branches: "**"
  pull_request:
    branches: "**"

  # Run this workflow manually?
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.8', '3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Setting up python
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Run a test file with django test
      - name: Install django requirements
        working-directory: ./src/backend
        run: |
          pip install -r requirements.txt
      # - name: Generate Random Key
      #   working-directory: ./src/backend
      #   run: |
      #     python3 generate_random_key.py
      - name: Test with django
        working-directory: ./src/backend
        run: |
          python3 manage.py migrate
          python3 manage.py test