# Basic workflow
name: Sample-testing

# Controls
on:
  # Triggers the workflow on push or pull request events on "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Run this workflow manually?
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Setting up python
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # Install all the dependencies required for the testing
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
          pip install pytest
      # Run a test file
      - name: Test with tox
        run: tox
      # Run pytest
      - name: pytest tests
        run: pytest